name: Build and Deploy Angular App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v4

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: 'Install Dependencies'
        # This tells the step to run 'npm install' inside the sub-folder
        working-directory: ./product-catalog-frontend 
        run: npm install

      - name: 'Build Project'
        # This tells the step to run 'npm run build' inside the sub-folder
        working-directory: ./product-catalog-frontend 
        run: npm run build -- --configuration production

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'product-webapp-ujwal'
          publish-profile: ${{ secrets.AZUREPUBLISHPROFILE }}
          # The package path is now inside the sub-folder
          package: './product-catalog-frontend/dist/product-catalog-frontend'